version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: ${INFLUXDB_NAME}
    restart: unless-stopped
    network_mode: 'bridge'
    ports:
      - ${INFLUXDB_HTTP_PORT}:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
      - INFLUXD_LOG_LEVEL=${INFLUXD_LOG_LEVEL}
      - TZ=${TZ}
    volumes:
      - influxdb:/var/lib/influxdb
  
  grafana:
    image: grafana/grafana:latest 
    container_name: grafana
    restart: unless-stopped
    network_mode: 'bridge'
    expose:
      - 3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=grafana_pwd
      - GF_AUTH_PROXY_AUTO_SIGN_UP=false
      - GF_AUTH_PROXY_ENABLED=true
    volumes:
      - grafana:/var/lib/grafana
    links:
      - ${INFLUXDB_NAME}
    depends_on:
      - ${INFLUXDB_NAME}
  
  speedtest:
    image: homeserver-speedtest-cli
    container_name: speedtest
    restart: unless-stopped
    network_mode: 'bridge'
    environment:
      - TEST_INTERVAL=300
      - WRITE_CSV=False
      - WRITE_INFLUXDB=False
      - WRITE_INFLUXDB2=True
      - INFLUXDB_HOST=${INFLUXDB_NAME}
      - INFLUXDB_ORG=${INFLUXDB_INIT_ORG}
      - INFLUXDB_PORT=${INFLUXDB_HTTP_PORT}
      - INFLUXDB_DB=${INFLUXDB_INIT_BUCKET}
      - INFLUXDB_USER=${INFLUXDB_INIT_USERNAME}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - speedtest:/var/lib/speedtest
    links:
      - ${INFLUXDB_NAME}
    depends_on:
      - ${INFLUXDB_NAME}
      
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    network_mode: 'bridge'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 81:81
      - 443:443
    links:
      - grafana
      - netdata
      - pihole
      - wordpress
    depends_on:
      - grafana
      - netdata
      - pihole
      - wordpress
      
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: 'bridge'
    restart: unless-stopped
    ports:
      - "93:53/tcp"
      - "93:53/udp"
      - "97:67/udp"
    expose:
      - 80
      - 443
    environment:
      TZ: 'Europe/Vienna'
      WEBPASSWORD: pihole_pwd
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
      
    
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: raspi.home # set to fqdn of host
    network_mode: 'bridge'
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    network_mode: 'bridge'
    ports:
      - 90:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
    links:
      - db

  db:
    image: linuxserver/mariadb:latest
    container_name: db
    restart: unless-stopped
    network_mode: 'bridge'
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
      
volumes:
  influxdb:
  grafana:
  speedtest:
  wordpress:
  db:
